name: Waka Readme

on:
  # 每天 UTC 时间 00:00 自动更新
  schedule:
    - cron: '0 0 * * *'
  # 支持手动触发
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # 使用我的用户名和电子邮件提交代码
          COMMIT_BY_ME: "False"
          # 设置提交信息
          COMMIT_MESSAGE: "Wakatime Github Readme Update"
          # 显示更新日期
          SHOW_UPDATED_DATE: "False"
          # 显示迄今为止编写的代码行数
          SHOW_LINES_OF_CODE: "True"
          # 个人资料视图
          SHOW_PROFILE_VIEWS: "False"
          # 提交内容具体时间的图表
          SHOW_COMMIT: "False"
          # 每周提交日期的图表
          SHOW_DAYS_OF_WEEK: "False"
          # 提交使用语言的图表
          SHOW_LANGUAGE: "True"
          # 显示使用的操作系统图表
          SHOW_OS: "True"
          # 显示提交到哪些存储库
          SHOW_PROJECTS: "False"
          # 显示提交所在的时区
          SHOW_TIMEZONE: "False"
          # 显示代码编辑器列表
          SHOW_EDITORS: "False"
          # 个人概要信息
          SHOW_SHORT_INFO: "False"
          # 显示不同极度编写代码的行数
          SHOW_LOC_CHART: "False"
          # 不想被计入的仓库
          # IGNORED_REPOS: ""
          # 显示每种语言的代码库数量
          SHOW_LANGUAGE_PER_REPO: "False"
